name: Release Please

on:
  workflow_call:
    inputs:
      config-file:
        required: false
        type: string
        default: 'release-please-config.json'
      manifest-file:
        required: false
        type: string
        default: '.release-please-manifest.json'
    outputs:
      release_created:
        description: "Whether a release was created"
        value: ${{ jobs.release-please.outputs.release_created }}
      tag_name:
        description: "The tag name of the created release"
        value: ${{ jobs.release-please.outputs.tag_name }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: ${{ inputs.config-file }}
          manifest-file: ${{ inputs.manifest-file }}
